const { withGradleProperties } = require('expo/config-plugins');

// The Expo template ships `-Xmx2048m -XX:MaxMetaspaceSize=512m`. Release builds run R8 with
// minify and resource shrinking enabled (see expo-build-properties in app.json), and R8 loads
// the whole program's classes to do it -- 512m of Metaspace is not enough for an RN 0.86 app
// with this dependency tree. The daemon dies with `OutOfMemoryError: Metaspace` at
// :app:packageRelease, which surfaces as "Failed to notify root build lifecycle listener >
// Metaspace" followed by "Could not receive a message from the daemon".
//
// Metaspace is the setting that actually matters here; the heap is raised alongside it because
// R8 is memory-hungry in both and a 4g heap is comfortable on any machine that can build this.
const JVM_ARGS = '-Xmx4096m -XX:MaxMetaspaceSize=2048m';

const KEY = 'org.gradle.jvmargs';

/**
 * Raises the Gradle daemon's JVM memory so release builds survive R8.
 *
 * Applied as a config plugin because android/ is gitignored / regenerated by
 * `expo prebuild`, so a direct gradle.properties edit would be discarded on the next prebuild
 * -- which is exactly what happens on every EAS build, local or hosted.
 */
function withGradleDaemonMemory(config) {
  return withGradleProperties(config, (cfg) => {
    const properties = cfg.modResults;
    const existing = properties.find((item) => item.type === 'property' && item.key === KEY);

    if (existing) {
      existing.value = JVM_ARGS;
    } else {
      properties.push({ type: 'property', key: KEY, value: JVM_ARGS });
    }

    return cfg;
  });
}

module.exports = withGradleDaemonMemory;
