const { withAppBuildGradle } = require('expo/config-plugins');

// AGP 8.x (RN 0.85) is compatible with desugar_jdk_libs 2.x.
const DESUGAR_JDK_LIBS = 'com.android.tools:desugar_jdk_libs:2.1.4';

/**
 * Enables Android core-library desugaring so newer JDK APIs (notably `java.time.*`)
 * resolve on API < 26.
 *
 * expo-dev-launcher's NsdDiscoveryBase references `java.time.Duration`, which only
 * exists natively on Android 8 (API 26)+. On the Android 7 (API 24/25) kiosk the
 * debug/dev-client build therefore crashes at MainApplication.onCreate with
 * NoClassDefFoundError before any JS runs. Desugaring back-ports those APIs.
 *
 * Applied as a config plugin because android/ is gitignored / regenerated by
 * `expo prebuild`, so a direct gradle edit would be discarded on the next prebuild.
 */
function withCoreLibraryDesugaring(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withCoreLibraryDesugaring only supports Groovy build.gradle');
    }

    let contents = cfg.modResults.contents;

    // 1) Enable desugaring in compileOptions — reuse the block if it exists,
    //    otherwise create one inside the top-level `android {}`.
    if (!contents.includes('coreLibraryDesugaringEnabled')) {
      if (/compileOptions\s*\{/.test(contents)) {
        contents = contents.replace(
          /compileOptions\s*\{/,
          (match) => `${match}\n        coreLibraryDesugaringEnabled true`
        );
      } else {
        contents = contents.replace(
          /^android\s*\{/m,
          (match) => `${match}\n    compileOptions {\n        coreLibraryDesugaringEnabled true\n    }`
        );
      }
    }

    // 2) Add the desugaring runtime to the app module's dependencies.
    if (!contents.includes('desugar_jdk_libs')) {
      contents = contents.replace(
        /^dependencies\s*\{/m,
        (match) => `${match}\n    coreLibraryDesugaring "${DESUGAR_JDK_LIBS}"`
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = withCoreLibraryDesugaring;
